/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistsIndexRouteImport } from './routes/checklists.index'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as AppsAuditIndexRouteImport } from './routes/apps-audit.index'
import { Route as AgeGuidesIndexRouteImport } from './routes/age-guides.index'
import { Route as ChecklistsSlugRouteImport } from './routes/checklists.$slug'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as AppsAuditSlugRouteImport } from './routes/apps-audit.$slug'
import { Route as AgeGuidesAgeRouteImport } from './routes/age-guides.$age'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsIndexRoute = ChecklistsIndexRouteImport.update({
  id: '/checklists/',
  path: '/checklists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAuditIndexRoute = AppsAuditIndexRouteImport.update({
  id: '/apps-audit/',
  path: '/apps-audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeGuidesIndexRoute = AgeGuidesIndexRouteImport.update({
  id: '/age-guides/',
  path: '/age-guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsSlugRoute = ChecklistsSlugRouteImport.update({
  id: '/checklists/$slug',
  path: '/checklists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAuditSlugRoute = AppsAuditSlugRouteImport.update({
  id: '/apps-audit/$slug',
  path: '/apps-audit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeGuidesAgeRoute = AgeGuidesAgeRouteImport.update({
  id: '/age-guides/$age',
  path: '/age-guides/$age',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/help': typeof HelpRoute
  '/news': typeof NewsRoute
  '/age-guides/$age': typeof AgeGuidesAgeRoute
  '/apps-audit/$slug': typeof AppsAuditSlugRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/checklists/$slug': typeof ChecklistsSlugRoute
  '/age-guides/': typeof AgeGuidesIndexRoute
  '/apps-audit/': typeof AppsAuditIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/checklists/': typeof ChecklistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/help': typeof HelpRoute
  '/news': typeof NewsRoute
  '/age-guides/$age': typeof AgeGuidesAgeRoute
  '/apps-audit/$slug': typeof AppsAuditSlugRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/checklists/$slug': typeof ChecklistsSlugRoute
  '/age-guides': typeof AgeGuidesIndexRoute
  '/apps-audit': typeof AppsAuditIndexRoute
  '/apps': typeof AppsIndexRoute
  '/checklists': typeof ChecklistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/help': typeof HelpRoute
  '/news': typeof NewsRoute
  '/age-guides/$age': typeof AgeGuidesAgeRoute
  '/apps-audit/$slug': typeof AppsAuditSlugRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/checklists/$slug': typeof ChecklistsSlugRoute
  '/age-guides/': typeof AgeGuidesIndexRoute
  '/apps-audit/': typeof AppsAuditIndexRoute
  '/apps/': typeof AppsIndexRoute
  '/checklists/': typeof ChecklistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/glossary'
    | '/help'
    | '/news'
    | '/age-guides/$age'
    | '/apps-audit/$slug'
    | '/apps/$slug'
    | '/checklists/$slug'
    | '/age-guides/'
    | '/apps-audit/'
    | '/apps/'
    | '/checklists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/glossary'
    | '/help'
    | '/news'
    | '/age-guides/$age'
    | '/apps-audit/$slug'
    | '/apps/$slug'
    | '/checklists/$slug'
    | '/age-guides'
    | '/apps-audit'
    | '/apps'
    | '/checklists'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/glossary'
    | '/help'
    | '/news'
    | '/age-guides/$age'
    | '/apps-audit/$slug'
    | '/apps/$slug'
    | '/checklists/$slug'
    | '/age-guides/'
    | '/apps-audit/'
    | '/apps/'
    | '/checklists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GlossaryRoute: typeof GlossaryRoute
  HelpRoute: typeof HelpRoute
  NewsRoute: typeof NewsRoute
  AgeGuidesAgeRoute: typeof AgeGuidesAgeRoute
  AppsAuditSlugRoute: typeof AppsAuditSlugRoute
  AppsSlugRoute: typeof AppsSlugRoute
  ChecklistsSlugRoute: typeof ChecklistsSlugRoute
  AgeGuidesIndexRoute: typeof AgeGuidesIndexRoute
  AppsAuditIndexRoute: typeof AppsAuditIndexRoute
  AppsIndexRoute: typeof AppsIndexRoute
  ChecklistsIndexRoute: typeof ChecklistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/': {
      id: '/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof ChecklistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps-audit/': {
      id: '/apps-audit/'
      path: '/apps-audit'
      fullPath: '/apps-audit/'
      preLoaderRoute: typeof AppsAuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-guides/': {
      id: '/age-guides/'
      path: '/age-guides'
      fullPath: '/age-guides/'
      preLoaderRoute: typeof AgeGuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists/$slug': {
      id: '/checklists/$slug'
      path: '/checklists/$slug'
      fullPath: '/checklists/$slug'
      preLoaderRoute: typeof ChecklistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps-audit/$slug': {
      id: '/apps-audit/$slug'
      path: '/apps-audit/$slug'
      fullPath: '/apps-audit/$slug'
      preLoaderRoute: typeof AppsAuditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-guides/$age': {
      id: '/age-guides/$age'
      path: '/age-guides/$age'
      fullPath: '/age-guides/$age'
      preLoaderRoute: typeof AgeGuidesAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GlossaryRoute: GlossaryRoute,
  HelpRoute: HelpRoute,
  NewsRoute: NewsRoute,
  AgeGuidesAgeRoute: AgeGuidesAgeRoute,
  AppsAuditSlugRoute: AppsAuditSlugRoute,
  AppsSlugRoute: AppsSlugRoute,
  ChecklistsSlugRoute: ChecklistsSlugRoute,
  AgeGuidesIndexRoute: AgeGuidesIndexRoute,
  AppsAuditIndexRoute: AppsAuditIndexRoute,
  AppsIndexRoute: AppsIndexRoute,
  ChecklistsIndexRoute: ChecklistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
